voting-sites:
  - "PlanetMinecraft.com|https://www.planetminecraft.com/server/siegemasters/vote/"
  - "MincraftServers.org|https://minecraftservers.org/vote/569726"
  - "Minecraft-MP.com|https://minecraft-mp.com/server/240125/vote/"
  - "Minecraft-Server.net|https://minecraft-server.net/vote/Zaxarner"
  - "TopG.org|https://topg.org/Minecraft/in-590118"
  - "Minecraft-Server-List.com|https://minecraft-server-list.com/server/449853/vote/"
  - "MinecraftServers.biz|https://minecraftservers.biz/servers/145941/#vote_now"
  - "EmeraldServers.com|https://emeraldservers.com/server/294"
tips:
  - "Press 1, 2, 3, and 4|to cast your Abilities!"
  - "Make sure you time your attacks|to ensure maximum damage!"
  - "Make sure you time your attacks|to ensure maximum damage!"
  - "Make sure you time your attacks|to ensure maximum damage!"
  - "Open your Inventory and|hover over the Abilities|to view a detailed description."
  - "Some weapons make you slower than others!|Customize your /Loadout to fit your playstyle!"
  - "Some weapons make you slower than others!|Customize your /Loadout to fit your playstyle!"
  - "There are more Abilities to unlock!|/Loadout"
  - "There are more Abilities to unlock!|/Loadout"
  - "Out of Arrows?|Right-Click a Fletching Table!"
  - "You cannot regenerate Stamina while sprinting."
  - "Shields are incredibly strong!|They can block most kinds of attacks.|However, they reduce your movement speed."
  - "Magick is used to cast Abilities with blue icons."
  - "Stamina is used to cast Abilities with green icons."
  - "You can view your Allies' Health below their names."
  - "Hearts appear around players when they are healed.|The number of hearts indicates how much."
removable-worlds:
  - "Crumbling_Castle"
  - "Monastery"